<a href="https://colab.research.google.com/github/ShinwooChoi/ESAA/blob/main/ESAA_YB_WEEK1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
array_zeros = np.zeros(10)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
array_size = np.array([1,2,3])
print(array_size.nbytes)

24


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
array_fifth = np.zeros(10)
array_fifth[4] = 1
print(array_fifth)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
array_10 = np.arange(10, 50)
print(array_10)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
array_reverse = np.array([0,1,2,3,4])
print(array_reverse[::-1])

[4 3 2 1 0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
array_3x3 = np.arange(9).reshape(3, 3)
print(array_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
array_nonzero = np.nonzero([1, 2, 0, 0, 4, 0])
print(array_nonzero[0])

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [11]:
matrix_1 = np.identity(3)
print(matrix_1)

matrix_2 = np.eye(3)
print(matrix_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [12]:
array_333 = np.random.random((3,3,3))
print(array_333)

[[[0.4416685  0.7256067  0.00560963]
  [0.71699215 0.42815626 0.6794502 ]
  [0.54946502 0.82146357 0.5945916 ]]

 [[0.85404608 0.25552037 0.65508292]
  [0.04581129 0.00661484 0.95679097]
  [0.37053924 0.126853   0.41907182]]

 [[0.31073153 0.08254036 0.90038179]
  [0.01446455 0.306192   0.57437877]
  [0.03509177 0.47577042 0.9352063 ]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [13]:
array_m = np.random.random((10,10))
print(array_m)
print(np.min(array_m))
print(np.max(array_m))

[[0.85559438 0.761071   0.39904879 0.13091533 0.81944073 0.85835612
  0.05059314 0.19161906 0.37456223 0.10214098]
 [0.74682864 0.05226369 0.9867634  0.06128098 0.62152109 0.31971299
  0.28002924 0.85726513 0.1946198  0.82925518]
 [0.64539988 0.80694756 0.84462679 0.74754388 0.42303034 0.80727302
  0.95226222 0.68782707 0.47501004 0.51843545]
 [0.67609131 0.57791909 0.46006155 0.45072129 0.37100288 0.78999716
  0.82724312 0.98964397 0.87527773 0.46922362]
 [0.82759897 0.18241802 0.77009663 0.86325691 0.20914529 0.61269276
  0.19119018 0.99633827 0.41950576 0.2326409 ]
 [0.26364068 0.32157402 0.77219084 0.30968976 0.45897585 0.52725394
  0.03542256 0.1051122  0.74305387 0.09351858]
 [0.37916549 0.2163057  0.11999341 0.07871421 0.85287463 0.96963984
  0.55047102 0.13498088 0.45770655 0.73194923]
 [0.28241891 0.52197147 0.63626931 0.82816717 0.21613978 0.23059659
  0.30888768 0.58875699 0.69092562 0.81949434]
 [0.13457488 0.5114445  0.70738905 0.29135618 0.50360051 0.50949422
  0.0163553 

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [14]:
array_mv = np.random.random(30)
print(array_mv)
print(np.mean(array_mv))

[0.61251539 0.535891   0.77254424 0.64522056 0.03340595 0.58826955
 0.79933921 0.19101784 0.49052717 0.99313948 0.9137037  0.54269658
 0.01676695 0.62178126 0.24473851 0.55771787 0.25260553 0.00834479
 0.0603197  0.52569408 0.43000117 0.03924338 0.55419952 0.01945134
 0.49991124 0.71830485 0.70453346 0.2583499  0.16657535 0.04017399]
0.4278994519704881


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
array_2d = np.ones((5,5))
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [18]:
array_dig = np.array([1, 2, 3, 4])
matrix = np.diag(array_dig, k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
array_check = np.zeros((8, 8))
array_check[1::2, ::2] = 1
array_check[::2, 1::2] = 1
print(array_check)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [21]:
array_index = np.unravel_index(99,(6,7,8))
print(array_index)

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [22]:
array_norm=np.random.random((5,5))
norm_mean=np.mean(array_norm)
norm_std=np.std(array_norm)
norm_array=(array_norm - norm_mean) / norm_std
print(norm_array)

[[-1.09533999e+00 -3.16771824e-01  5.75382389e-01 -1.22353636e+00
  -2.70999928e-01]
 [ 1.48661525e+00  1.33854548e+00 -4.28415170e-02 -1.28979903e+00
   1.66912535e+00]
 [ 1.54943556e+00 -4.16761091e-02  5.55641880e-04 -6.44850323e-01
   1.12721944e+00]
 [-3.48905684e-01 -1.14203418e+00  1.24640893e-01 -1.41538186e+00
  -1.22077986e-01]
 [ 1.42300913e+00 -4.79176292e-01 -1.48242418e+00  1.06939342e+00
  -4.48107297e-01]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [24]:
array_color=np.dtype([('R', np.ubyte),
 ('G', np.ubyte),
  ('B', np.ubyte),
   ('A', np.ubyte)])
print(array_color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
