<a href="https://colab.research.google.com/github/ShinwooChoi/ESAA/blob/main/YB0307_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [11]:
import numpy as np

A = np.random.random((5,3))
B = np.random.random((3,2))

print("5X3 matrix:\n", A)
print("3X2 matrix:\n", B)
print("Multiply two matrix:\n", np.dot(A,B))

5X3 matrix:
 [[0.86605393 0.44361745 0.72655749]
 [0.65297927 0.76475029 0.98983854]
 [0.273942   0.493184   0.09210648]
 [0.06108652 0.874082   0.06865089]
 [0.30009696 0.12957453 0.76801912]]
3X2 matrix:
 [[0.12062542 0.90709269]
 [0.22711902 0.93658395]
 [0.96074057 0.6192217 ]]
Multiply two matrix:
 [[0.90325533 1.65097632]
 [1.20343327 1.92149507]
 [0.23354626 0.76743334]
 [0.27184492 0.91657242]
 [0.80349528 0.86914728]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [12]:
array1 = np.arange(10)
array1[(3 < array1) & (array1 < 8)] *= -1
print(array1)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9 10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)₩
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

1. 유효
2. 유효
3. 무효: '<-'는 존재하지 않는 연산자 (SyntaxError)
4. 유효
5. 유효
6. 무효: 잘못된 비교 연산 (ValueError)


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

- 0 / 0 은 수학적으로 정의되지 않음.
- 0 // 0 정수 나눗셈 역시 정의되지 않음.
- 이때, '/'와 '//'의 차이점은 '/'은 실수형 나눗셈, '//'은 나눈 후 내림 결과 도출
- NaN을 값을 포함한 배열 생성 -> 정수형으로 변환 -> 실수형으로 변환

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [13]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)

common_values = np.intersect1d(Z1, Z2)
print(common_values)


[5 3 9 3 9 0 3 8 0 6]
[1 6 9 8 2 6 8 2 6 9]
[6 8 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j

False, emath가 복소수

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)₩
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [14]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [15]:
A = np.random.rand(3, 3) #3X3 랜덤 배열 생성
B = np.random.rand(3, 3)

C = np.add(A, B)

D = np.divide(A, -2)

E = np.multiply(A, A)

print(E)

[[0.86125303 0.28035233 0.00108288]
 [0.71925642 0.02572106 0.02352705]
 [0.44407714 0.5487657  0.7459994 ]]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [16]:
array2 = np.random.uniform(0, 10, 10)

# 방법 1: np.floor() 사용
int_part1 = np.floor(array2).astype(int)

# 방법 2: astype를 사용
int_part2 = array2.astype(int)

print("원본 배열:", array2)
print("방법 1:", int_part1)
print("방법 2:", int_part2)

원본 배열: [5.52519402 7.99417295 7.30798102 5.44756305 9.18943755 4.78325289
 4.11485724 3.10554105 3.56902958 9.48885598]
방법 1: [5 7 7 5 9 4 4 3 3 9]
방법 2: [5 7 7 5 9 4 4 3 3 9]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [28]:
matrix = np.tile(np.arange(5), (5, 1))

print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)₩

In [27]:
vector = np.random.rand(10)

sorted_vector = np.sort(vector)

print("Original Vector:\n", vector)
print("Sorted Vector:\n", sorted_vector)


Original Vector:
 [0.68924219 0.45774237 0.95574173 0.21489705 0.44979478 0.06558158
 0.05994053 0.08926584 0.8605815  0.48408893]
Sorted Vector:
 [0.05994053 0.06558158 0.08926584 0.21489705 0.44979478 0.45774237
 0.48408893 0.68924219 0.8605815  0.95574173]



#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [18]:

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(np.array_equal(A,B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [19]:
# 랜덤 행렬 생성
cartesian_matrix = np.random.rand(10, 2)

# 극좌표 변환
r = np.sqrt(cartesian_matrix[:, 0]**2 + cartesian_matrix[:, 1]**2)
theta = np.arctan2(cartesian_matrix[:, 1], cartesian_matrix[:, 0])

# 결과 출력
print("Cartesian Coordinates:", cartesian_matrix)
print("\nPolar Coordinates:", np.column_stack((r, theta)))

Cartesian Coordinates: [[0.56093009 0.95168969]
 [0.23793921 0.15983269]
 [0.12465523 0.56140949]
 [0.02672459 0.16247013]
 [0.930084   0.7350399 ]
 [0.24075505 0.67376779]
 [0.79899631 0.75924909]
 [0.40874606 0.95107897]
 [0.70634081 0.86872845]
 [0.07598163 0.51727517]]

Polar Coordinates: [[1.10469717 1.03820414]
 [0.28663838 0.59150496]
 [0.57508221 1.35230126]
 [0.16465341 1.40776698]
 [1.18547033 0.66879463]
 [0.71549007 1.22760958]
 [1.10220429 0.75989602]
 [1.03519301 1.16489164]
 [1.11964568 0.88813392]
 [0.52282579 1.42495106]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [20]:
Z = np.random.random(10)
maximum_index = Z.argmax()
Z[maximum_index]=0
Z


array([0.75946997, 0.88543218, 0.5558448 , 0.52081273, 0.03914472,
       0.8413004 , 0.93185531, 0.96942087, 0.        , 0.88520641])

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [21]:
Z = np.array([0.44543135, 0.15272685, 0.        , 0.87774566, 0.23038287,
       0.63059028, 0.85004996, 0.4217004 , 0.87033034, 0.32653317])

v = np.random.uniform(0, 100)

dist = np.abs(Z - v)

index = np.argmin(dist)

closest_value = Z[index]

print("Closest value in a vector Z:", closest_value)


Closest value in a vector Z: 0.87774566


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [22]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z): # enumerate() - (인덱스,값)을 동시에 반환하는 함수 / index() - 인덱스만 반환하는 함수

    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [23]:
n = 3
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),8)
print(Z)

[[0. 0. 0.]
 [0. 0. 8.]
 [0. 0. 8.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [24]:
array39_1 = np.array([[1, 7, 3],
                     [9, 0, 1],
                     [8, 6, 4]])
indices = [0,2,1]
answer39_1 = array39_1[indices]
print(array39_1,'\n\n',answer39_1)

[[1 7 3]
 [9 0 1]
 [8 6 4]] 

 [[1 7 3]
 [8 6 4]
 [9 0 1]]


In [25]:
array39_2 = np.array([[7, 6, 7],
                    [7, 8, 4],
                    [5, 4, 7]])
indices = [2,0,1]
answer39_2 = array39_2[indices]
print(array39_2,'\n\n',answer39_2)

[[7 6 7]
 [7 8 4]
 [5 4 7]] 

 [[5 4 7]
 [7 6 7]
 [7 8 4]]


In [26]:
array39_3 = np.array([[7, 9, 5],
                      [1, 8, 2],
                      [6, 8, 1]])
indices = [2,1,0]
answer39_3 = array39_3[indices]
print(array39_3,'\n\n',answer39_3)

[[7 9 5]
 [1 8 2]
 [6 8 1]] 

 [[6 8 1]
 [1 8 2]
 [7 9 5]]
